name: CI

on:
  push:
    branches:
    - master
    - develop

jobs:

  test:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ‘1.14.0’

    - name: Test
      run: go test -v ./...

  